export const FETCH_DECKS = 'FETCH_DECKS'
export const ADD_DECK = 'ADD_DECK'
export const FETCH_DECK = 'FETCH_DECK'
export const ADD_QUESTION = 'ADD_QUESTION'
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'